---
- name: Ensure old boto versions are not installed.
  apt:
    pkg: ["python-botocore", "python-urllib3"]
    state: absent

- name: Ensure boto3 is installed.
  ansible.builtin.pip:
    name: boto3
