---
- name: Install Postfix
  ansible.builtin.apt:
    pkg: postfix
    state: present

- name: Install procmail
  ansible.builtin.apt:
    pkg: procmail
    state: present

- name: Copy master config
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "/etc/postfix/"
    owner: root
    group: root
    mode: "0755"
  with_items:
    - master.cf

- name: Configure mailname
  ansible.builtin.template:
    src: "mailname.j2"
    dest: "/etc/mailname"
    owner: root
    group: root
    mode: "0644"

- name: Configure main.cf
  ansible.builtin.template:
    src: "main.cf.j2"
    dest: "/etc/postfix/main.cf"
    owner: root
    group: root
    mode: "0644"
  notify: Reload Postfix configuration.

- name: Configure transport
  ansible.builtin.template:
    src: "transport.j2"
    dest: "/etc/postfix/transport"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload Postfix configuration.

- name: Initialise transport db
  ansible.builtin.command:
    cmd: /usr/sbin/postmap /etc/postfix/transport

- name: Install SASL
  ansible.builtin.package:
    name: libsasl2-modules
    state: present
  when: postfix.use_ses

- name: Configure SASL
  ansible.builtin.template:
    src: "sasl_passwd.j2"
    dest: "/etc/postfix/sasl_passwd"
    owner: root
    group: root
    mode: "0644"
  when: postfix.use_ses
  notify:
    - Reload Postfix configuration.

- name: Initialise sasl_passwd.
  ansible.builtin.command:
    cmd: /usr/sbin/postmap /etc/postfix/sasl_passwd
  when: postfix.use_ses

- name: Configure virtual.
  ansible.builtin.template:
    src: "virtual.j2"
    dest: "/etc/postfix/virtual"
    owner: root
    group: root
    mode: "0644"
  when: postfix.forward
  notify:
    - Initialise virtual.
    - Reload Postfix configuration.

- name: Configure mail aliases.
  ansible.builtin.template:
    src: aliases.j2
    dest: /etc/aliases
    owner: root
    group: root
    mode: 0644
  when: postfix.aliases | length > 0

- name: Ensure host maildir exists.
  ansible.builtin.file:
    path: "/home/ce-dev/var/Maildir"
    state: directory
  when:
    - postfix.ce_dev_delivery_mode == "host"
    - is_local is defined
    - is_local

- name: Configure procmail to NULL.
  ansible.builtin.template:
    src: procmailrc_null.j2
    dest: "/etc/procmailrc"
    owner: root
    group: root
    mode: "0644"
    force: true
  when:
    - is_local is defined
    - is_local

- name: Configure procmail to host directory.
  ansible.builtin.template:
    src: procmailrc_host.j2
    dest: "/etc/procmailrc"
    owner: root
    group: root
    mode: "0644"
    force: true
  when:
    - postfix.ce_dev_delivery_mode == "host"
    - is_local is defined
    - is_local

- name: Configure procmail to local.
  ansible.builtin.file:
    path: /etc/procmailrc
    state: absent
  when:
    - postfix.ce_dev_delivery_mode == "local"
    - is_local is defined
    - is_local

# Needed for Docker.
- name: Stop Postfix
  ansible.builtin.command:
    cmd: /usr/sbin/service postfix stop

- name: Remove trailing lock files.
  ansible.builtin.file:
    path: "{{ lock_file }}"
    state: absent
  with_items:
    - /var/spool/postfix/pid/master.pid
    - /var/lib/postfix/master.lock
  loop_control:
    loop_var: lock_file

- name: Create Postfix Aliases database
  ansible.builtin.command:
    cmd: /usr/bin/newaliases

- name: Restart Postfix
  ansible.builtin.command:
    cmd: /usr/sbin/service postfix start
