---
dependencies:
  - { role: ssh_server, when: ( is_local is not defined or not is_local ) }
  - role: _meta/common_base
  - role: user_provision
  - role: user_deploy
  - role: mysql_client
  - role: nodejs
  - role: php-cli
  - role: php-fpm
  - role: nginx
