---
collections:
  - name: ansible.posix
  - name: ansible.utils
  - name: community.sops
  - name: community.aws
  - name: community.general
  - name: amazon.aws

roles:
  - name: geerlingguy.varnish
  - name: geerlingguy.firewall
  - name: geerlingguy.composer
  - name: geerlingguy.clamav
  - name: robertdebock.openvpn
