---
aws_cli:
  version: latest # Specify a particular version number in X.X.X format to override
  refresh: false # Set to true to upgrade or downgrade the AWS client, which also clears out install files in /opt/aws-cli